# Header
menu:
  home: /
  archives: /archives
rss: /atom.xml

# Schema
color: blue

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
#favicon: /favicon.png

# Comments
## Disqus
disqus_shortname:
## Gitment
gitment:
  github_user:
  github_repo:
  client_id:
  client_secret:


# Site analytics
google_analytics:
cnzz_analytics:
tencent_analytics:
